version: '3'

networks:
  amq-network:
    driver: overlay

services:
  amq-primary-broker:
    image: rmohr/activemq:5.15.9

    volumes:
      - ./amq-configs/primary:/opt/activemq/conf
      - ./amq-kahadb:/opt/activemq/data/kahadb

    networks:
      amq-network:
        aliases:
          - primary

    ports:
        - 11111:61616
        - 11180:8161

  amq-secondary-broker:
    image: rmohr/activemq:5.15.9

    volumes:
      - ./amq-configs/secondary:/opt/activemq/conf
      - ./amq-kahadb:/opt/activemq/data/kahadb

    networks:
      amq-network:
        aliases:
          - secondary

    ports:
        - 22222:61616
        - 22280:8161

